apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-${VERSION_COLOUR}-deployment
  labels:
    app: frontend            #pods will be named app: user-service
    version: "${FRONTEND_VERSION}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      version: "${FRONTEND_VERSION}"
  template:
    metadata:
      labels:
        app: frontend
        version: "${FRONTEND_VERSION}"
    spec:
      nodeSelector:
        arch: arm64
    spec:
      containers:                     #specifies the container image the pods will run
        - name: frontend
          image: 822298509516.dkr.ecr.us-east-1.amazonaws.com/blue_green_ecr/frontend:${FRONTEND_VERSION}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-${VERSION_COLOUR}-service
  labels:
    app: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
    version: "${FRONTEND_VERSION}"
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
