apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres # Select pods with label app=mongodb
  ports:
    - protocol: TCP
      port: 5432 # Service Port
      targetPort: 5432 # Pods Port