name: Blue-green deployment on prod
on:
  workflow_dispatch:
  workflow_run:
    workflows: [ "Blue-green deployment on uat" ]
    types:
      - completed


jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Infrastructure Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

#      - name: cleanup
#        run: |
#          aws eks update-kubeconfig --region us-east-1 --name eks-blue-green
#          kubectl delete deployments --all -n uat-green
#          kubectl delete services --all -n uat-green

      - name: Deploy new green frontend version on prod
        run: |
          cd k8s/prod
          bash deploy_green.sh    

      - name: Run integration tests on prod.if successful, switch prod to green
        run: |
          cd k8s
          bash ./test_2.sh
          if [ $? -ne 0 ]; then
              echo "Tests failed"
              echo "deleting deployment"
              kubectl delete deployments --all -n prod-green
          else
              echo "All tests passed.deployment successful"
              sh ./change_to_prod.sh "prod-blue" "prod-green"
          fi
          exit
          EOF
