name: Nightly Build

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Infrastructure Repository
        uses: actions/checkout@v4

      - name: Checkout Source Repository
        uses: actions/checkout@v4
        with:
          repository: "likhithabz55/todolist-app"
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set date range
        run: |
            YESTERDAY=$(date -u -d "24 hours ago" +%Y-%m-%dT%H:%M:%S)
            echo "since_time=$YESTERDAY" >> $GITHUB_ENV

      - name: Get commit messages from last 24h
        id: commits
        run: |
            COMMITS=$(git log --since="${{ env.since_time }}" --pretty=format:"%s")
            echo "commit_messages=$COMMITS" >> $GITHUB_OUTPUT

      - name: Determine highest level change
        id: level
        run: |
          LEVEL="patch"
          
          # Check for BREAKING CHANGE (major bump)
          if echo "${{ env.commit_messages }}" | grep -qi "BREAKING CHANGE"; then
            LEVEL="major"
          
          elif echo "${{ env.commit_messages }}" | grep -qiE "^feat"; then
            LEVEL="minor"
          fi
          
          echo "Version bump level should be: $LEVEL"
          echo "level=$LEVEL" >> $GITHUB_ENV  # Store version bump level in environment variable   

      - name: Output bump level
        run: |
            echo "Version bump level: ${{ env.level }}"