name: Build green version on qa
on:
  workflow_run:
    workflows: [ "Nightly Build" ]
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Infrastructure Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: fetch and check if images are latest
        run: |
          sh k8s/fetch_latest_images.sh

      - name: Deploy new frontend version on qa
        run: |
          cd k8s/qa
          sh deploy.sh

      - name: Run tests
        run: |
          cd k8s/qa
          bash test_2.sh
          if [ $? -ne 0 ]; then
              echo "Tests failed"
              echo "deleting deployment"
              kubectl delete deployments --all -n qa
          else
              echo "All tests passed.deployment successful"
          fi
          exit
          EOF