name: Nightly Build

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Infrastructure Repository
        uses: actions/checkout@v4

      - name: Checkout Source Repository
        uses: actions/checkout@v4
        with:
          repository: "likhithabz55/todolist-app"
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set date range
        run: |
            YESTERDAY=$(date -u -d "24 hours ago" +%Y-%m-%dT%H:%M:%S)
            echo "since_time=$YESTERDAY" >> $GITHUB_ENV

      - name: Get commit messages from last 24h
        id: commits
        run: |
            COMMITS=$(git log --since="${{ env.since_time }}" --pretty=format:"%s")
            ESCAPED_COMMITS=$(echo "$COMMITS" | jq -sRr @uri)
            echo "commit_messages=$ESCAPED_COMMITS" >> $GITHUB_OUTPUT
          

      - name: Debug commit messages
        id: debug
        run: |
            ENCODED="${{ steps.commits.outputs.commit_messages }}"
        
            # Decode using printf and sed
            DECODED=$(printf '%b' "${ENCODED//%/\\x}")
            echo "Decoded commit messages:"
            echo "$DECODED"
        
            echo "decoded_commit_messages<<EOF" >> "$GITHUB_OUTPUT"
            echo "$DECODED" >> "$GITHUB_OUTPUT"
            echo "EOF" >> "$GITHUB_OUTPUT"


      - name: Determine highest level change
        id: level
        run: |
          LEVEL="patch"
          echo "Commit messages from last 24 hours:"
          echo "${{ steps.decode.outputs.decoded_commit_messages }}"
          
          # Check for BREAKING CHANGE (major bump)
          if echo "${{ steps.decode.outputs.decoded_commit_messages }}" | grep -qi "BREAKING CHANGE"; then
            LEVEL="major"
          
          elif echo "${{ steps.decode.outputs.decoded_commit_messages }}" | grep -qiE "^feat"; then
            LEVEL="minor"
          fi
          
          echo "Version bump level should be: $LEVEL"
          echo "level=$LEVEL" >> $GITHUB_ENV  # Store version bump level in environment variable   

      - name: Output bump level
        run: |
            echo "Version bump level: ${{ env.level }}"