name: Blue-green deployment on uat
on:
  workflow_run:
    workflows: [ "Build green version on qa" ]
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Infrastructure Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Deploy new green frontend version on uat
        run: |
          cd k8s/uat
          sh deploy_green.sh

      - name: Run integration tests on uat
        run: |
          sh ./test_2.sh
          if [ $? -ne 0 ]; then
              echo "Tests failed"
              echo "deleting deployment"
              kubectl delete deployments --all -n uat-green
          else
              echo "All tests passed.deployment successful"
          fi
          exit
          EOF
